-- =====================================================
-- 01_schema.sql
-- Administrador de Blog — Bases de Datos Avanzadas
-- Integrante 1: Arquitectura de Base de Datos (DBA)
-- =====================================================

-- ---------- TABLAS PRINCIPALES ----------

CREATE TABLE users (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE
);

CREATE TABLE articles (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title    VARCHAR2(200) NOT NULL,
    pub_date DATE DEFAULT SYSDATE,
    text     CLOB,
    user_id NUMBER NOT NULL,
    CONSTRAINT fk_articles_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- comments corregida: content + creation_date, FK a users y articles
CREATE TABLE comments (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content       CLOB,
    creation_date DATE DEFAULT SYSDATE,
    user_id       NUMBER NOT NULL,
    article_id    NUMBER NOT NULL,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE
);

CREATE TABLE tags (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url  VARCHAR2(200)
);

CREATE TABLE categories (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url  VARCHAR2(200)
);

-- ---------- TABLAS PUENTE (N:M) ----------

CREATE TABLE article_tags (
    article_id NUMBER NOT NULL,
    tag_id     NUMBER NOT NULL,
    CONSTRAINT pk_article_tags PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_at_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_at_tag FOREIGN KEY (tag_id)
        REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE article_categories (
    article_id  NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT pk_article_categories PRIMARY KEY (article_id, category_id),
    CONSTRAINT fk_ac_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_ac_category FOREIGN KEY (category_id)
        REFERENCES categories(id) ON DELETE CASCADE
);

-- ---------- DATOS SEMILLA (MOCK DATA) ----------

INSERT INTO users (name, email) VALUES ('Ana Torres', 'ana@correo.com');
INSERT INTO users (name, email) VALUES ('Luis Fernández', 'luis@correo.com');
INSERT INTO users (name, email) VALUES ('Carla Gómez', 'carla@correo.com');

INSERT INTO tags (name, url) VALUES ('Tecnología', '/tags/tecnologia');
INSERT INTO tags (name, url) VALUES ('Oracle', '/tags/oracle');
INSERT INTO tags (name, url) VALUES ('Python', '/tags/python');
INSERT INTO tags (name, url) VALUES ('Bases de Datos', '/tags/bases-de-datos');
INSERT INTO tags (name, url) VALUES ('Tutorial', '/tags/tutorial');

INSERT INTO categories (name, url) VALUES ('Desarrollo', '/categorias/desarrollo');
INSERT INTO categories (name, url) VALUES ('Educación', '/categorias/educacion');
INSERT INTO categories (name, url) VALUES ('Noticias', '/categorias/noticias');

INSERT INTO articles (title, text, user_id)
    VALUES ('Introducción a PL/SQL', 'Este artículo cubre los conceptos básicos de PL/SQL para trabajar con Oracle.', 1);
INSERT INTO articles (title, text, user_id)
    VALUES ('Conectando Python con Oracle', 'En este artículo exploramos el conector oracledb y sus buenas prácticas.', 2);

COMMIT;