-- 01_schema.sql — Modelo relacional del blog (ejecutar como BLOG_ADMIN).
-- DROP CASCADE reinicia datos del volumen. Relaciones:
--   users 1──N articles | users 1──N comments | articles 1──N comments
--   articles N──N tags (article_tags) | articles N──N categories (article_categories)
-- ON DELETE CASCADE en FKs: al borrar artículo/usuario/tag/categoría se limpia lo asociado.

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE article_tags CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE article_categories CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE comments CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE articles CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE tags CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE users (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE
);

CREATE TABLE articles (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title    VARCHAR2(200) NOT NULL,
    pub_date DATE DEFAULT SYSDATE,
    text     CLOB,
    user_id  NUMBER NOT NULL,
    CONSTRAINT fk_articles_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content       CLOB,
    creation_date DATE DEFAULT SYSDATE,
    user_id       NUMBER NOT NULL,
    article_id    NUMBER NOT NULL,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE
);

CREATE TABLE tags (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url  VARCHAR2(200)
);

CREATE TABLE categories (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url  VARCHAR2(200)
);

CREATE TABLE article_tags (
    article_id NUMBER NOT NULL,
    tag_id     NUMBER NOT NULL,
    CONSTRAINT pk_article_tags PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_at_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_at_tag FOREIGN KEY (tag_id)
        REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE article_categories (
    article_id  NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT pk_article_categories PRIMARY KEY (article_id, category_id),
    CONSTRAINT fk_ac_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_ac_category FOREIGN KEY (category_id)
        REFERENCES categories(id) ON DELETE CASCADE
);

-- Datos dummy
INSERT INTO users (name, email) VALUES ('Demo User', 'demo@correo.com');
INSERT INTO users (name, email) VALUES ('Ana Torres', 'ana@correo.com');

INSERT INTO tags (name, url) VALUES ('Demo Tag', '/tags/demo');

INSERT INTO categories (name, url) VALUES ('Demo Cat', '/categorias/demo');

INSERT INTO articles (title, text, user_id)
SELECT 'Artículo demo', 'Texto de ejemplo para semilla.', id
FROM users WHERE email = 'demo@correo.com';

INSERT INTO comments (content, user_id, article_id)
SELECT 'Comentario demo de prueba.', u.id, a.id
FROM users u, articles a
WHERE u.email = 'demo@correo.com' AND a.title = 'Artículo demo';

INSERT INTO article_tags (article_id, tag_id)
SELECT a.id, t.id
FROM articles a, tags t
WHERE a.title = 'Artículo demo' AND t.name = 'Demo Tag';

INSERT INTO article_categories (article_id, category_id)
SELECT a.id, c.id
FROM articles a, categories c
WHERE a.title = 'Artículo demo' AND c.name = 'Demo Cat';

COMMIT;
