-- =====================================================
-- 01_schema.sql
-- Proyecto: Administrador de Blog — Bases de Datos Avanzadas
-- Rol: Integrante 1 - Arquitectura de Base de Datos (DBA)
-- Descripción: Script DDL para la creación de la estructura base
--              y poblado inicial de datos (Mock Data).
-- =====================================================

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE article_tags CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE article_categories CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE comments CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE articles CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE tags CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- -----------------------------------------------------
-- 1. TABLAS PRINCIPALES (Entidades Fuertes)
-- -----------------------------------------------------

-- Tabla de Usuarios: Almacena los autores de artículos y comentarios.
CREATE TABLE users (
    id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE
);

-- Tabla de Artículos: Publicaciones del blog.
-- Se usa CLOB para permitir textos largos, tal como exige el requerimiento.
CREATE TABLE articles (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title    VARCHAR2(200) NOT NULL,
    pub_date DATE DEFAULT SYSDATE,
    text     CLOB,
    user_id  NUMBER NOT NULL,
    CONSTRAINT fk_articles_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de Comentarios (Estructura Corregida):
-- Relaciona un comentario con su autor y el artículo al que pertenece.
CREATE TABLE comments (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content       CLOB,
    creation_date DATE DEFAULT SYSDATE,
    user_id       NUMBER NOT NULL,
    article_id    NUMBER NOT NULL,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE
);

-- Tabla de Etiquetas (Tags): Metadatos para clasificar artículos.
CREATE TABLE tags (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url  VARCHAR2(200)
);

-- Tabla de Categorías: Clasificación jerárquica de los artículos.
CREATE TABLE categories (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url  VARCHAR2(200)
);

-- -----------------------------------------------------
-- 2. TABLAS PUENTE (Relaciones N:M)
-- -----------------------------------------------------

-- Relación Artículo <-> Etiqueta (N:M)
-- Integridad: ON DELETE CASCADE asegura que no queden registros huérfanos.
CREATE TABLE article_tags (
    article_id NUMBER NOT NULL,
    tag_id     NUMBER NOT NULL,
    CONSTRAINT pk_article_tags PRIMARY KEY (article_id, tag_id),
    CONSTRAINT fk_at_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_at_tag FOREIGN KEY (tag_id)
        REFERENCES tags(id) ON DELETE CASCADE
);

-- Relación Artículo <-> Categoría (N:M)
CREATE TABLE article_categories (
    article_id  NUMBER NOT NULL,
    category_id NUMBER NOT NULL,
    CONSTRAINT pk_article_categories PRIMARY KEY (article_id, category_id),
    CONSTRAINT fk_ac_article FOREIGN KEY (article_id)
        REFERENCES articles(id) ON DELETE CASCADE,
    CONSTRAINT fk_ac_category FOREIGN KEY (category_id)
        REFERENCES categories(id) ON DELETE CASCADE
);

-- -----------------------------------------------------
-- 3. DATOS SEMILLA (Mock Data Obligatorio)
-- -----------------------------------------------------

-- 3 Usuarios de prueba
INSERT INTO users (name, email) VALUES ('Ana Torres', 'ana@correo.com');
INSERT INTO users (name, email) VALUES ('Luis Fernández', 'luis@correo.com');
INSERT INTO users (name, email) VALUES ('Carla Gómez', 'carla@correo.com');

-- 5 Etiquetas de prueba
INSERT INTO tags (name, url) VALUES ('Tecnología', '/tags/tecnologia');
INSERT INTO tags (name, url) VALUES ('Oracle', '/tags/oracle');
INSERT INTO tags (name, url) VALUES ('Python', '/tags/python');
INSERT INTO tags (name, url) VALUES ('Bases de Datos', '/tags/bases-de-datos');
INSERT INTO tags (name, url) VALUES ('Tutorial', '/tags/tutorial');

-- 3 Categorías de prueba
INSERT INTO categories (name, url) VALUES ('Desarrollo', '/categorias/desarrollo');
INSERT INTO categories (name, url) VALUES ('Educación', '/categorias/educacion');
INSERT INTO categories (name, url) VALUES ('Noticias', '/categorias/noticias');

-- 2 Artículos de prueba
INSERT INTO articles (title, text, user_id)
    VALUES ('Introducción a PL/SQL', 'Este artículo cubre los conceptos básicos de PL/SQL para trabajar con Oracle.', 1);
INSERT INTO articles (title, text, user_id)
    VALUES ('Conectando Python con Oracle', 'En este artículo exploramos el conector oracledb y sus buenas prácticas.', 2);

-- Guardamos todos los datos (Commit)
COMMIT;